- hosts: all
  gather_facts: no
  connection: local

  tasks:
    - debug: var=inventory_hostname
    - debug: var=username
    - debug: var=password
    
    - name: Collect all BIG-IP facts
      bigip_device_facts:
        gather_subset:
          - devices
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ username }}"
          password: "{{ password }}"
          transport: rest
          validate_certs: no
      delegate_to: localhost
      register: device_info
     
     - debug: var=device_info.stdout_lines

